name: cumt_login
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0 # 本地存储
  dio: ^5.1.1 # 网络请求
  flutter_picker: ^2.1.0 # 选择器, 用于选择校区和运营商
  cupertino_icons: ^1.0.2 # iOS图标
  image_picker: ^0.8.7+1 # 图片选择，用于访问本地相册

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

