name: cumt_login
description: A new Flutter project.

publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.1.0 # 本地存储
  dio: ^5.1.1 # 网络请求
  flutter_picker: ^2.1.0 # 选择器, 用于选择校区和运营商
  cupertino_icons: ^1.0.2 # iOS图标
  flutter_screenutil: ^5.7.0 # 屏幕适配
  image_picker: ^0.8.7 # 图片选择，用于访问本地相册
  getwidget: ^3.0.1 # 一个ui组件库
  cached_network_image: ^3.2.1 #缓存网络图片
  material_design_icons_flutter: ^6.0.7096 #icon
  url_launcher: ^6.1.10   #进行app外页面访问
  provider: ^6.0.5 #状态管理，
  package_info: any   #调取本地的版本信息
  bot_toast: ^4.0.3   #错误弹窗
  firebase_core: ^2.10.0  #firebase 用户监控
  firebase_analytics: ^10.2.1 #用户行为监控

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/